### ISSUE TITLE
Error: subscript contains out-of-bounds indices

### ISSUE THREAD

**Issue by MaestSi** [haowulab/TRESS#1]
Dear developers,
I am running TRESS_1.0.0 on a small genome, using 4 replicates of IP and Input, all with high coverage (~1000x), with the following instruction:
```
TRESS_peak(IP.file = basename(bam_files_IP_curr),
             Input.file = basename(bam_files_input_curr),
             Path_To_AnnoSqlite = annotation_sqlite,
             InputDir = input_dir,
             OutputDir = output_dir,
             experiment_name = peaks_curr,
             filetype = "bam",
             IncludeIntron = FALSE,
             binsize = 50,
             WhichThreshold = fdr_lfc,
             pval.cutoff0 = 0.00001,
             fdr.cutoff0 = 0.05,
             lfc.cutoff0 = 0.7,
             lowcount = 30)

```
However, I get the following output:
```
##### Divid the genome into bins and obtain bin counts...
Error: subscript contains out-of-bounds indices

```
In the past I've been able to run TRESS successfully, but it looks like this time there is something different going on. Could you suggest what might cause the issue?
Thanks in advance,
Simone

**Comment by ZhenxingGuo0015** [comment]
Hi @MaestSi,

Could you please tell which genome you were using? Thanks.

Zhenxing

**Comment by MaestSi** [comment]
I'm studying RNA modifications in SARS-CoV-2.
Best,
Simone

**Comment by ZhenxingGuo0015** [comment]
Hi @MaestSi 

 Could you please run the following code on your TXDB file, and see what you got?
  > tmp = unique(genes(txdb))
  > head(tmp)
  > unique(seqnames(tmp))
  
Thanks,
Zhenxing

**Comment by MaestSi** [comment]
Here are the commands and the output:
```
tmp = unique(genes(txdb))
head(tmp)
unique(seqnames(tmp))

GRanges object with 6 ranges and 1 metadata column:
                       seqnames      ranges strand |            gene_id
                          <Rle>   <IRanges>  <Rle> |        <character>
  ENSSASG00005000002 MN908947.3   266-21555      + | ENSSASG00005000002
  ENSSASG00005000003 MN908947.3   266-13483      + | ENSSASG00005000003
  ENSSASG00005000004 MN908947.3 21563-25384      + | ENSSASG00005000004
  ENSSASG00005000005 MN908947.3 28274-29533      + | ENSSASG00005000005
  ENSSASG00005000006 MN908947.3 25393-26220      + | ENSSASG00005000006
  ENSSASG00005000007 MN908947.3 26523-27191      + | ENSSASG00005000007
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
[1] MN908947.3
Levels: MN908947.3

```

**Comment by ZhenxingGuo0015** [comment]
Hi @MaestSi,

My apologies. The reason TRESS reported an error is that currently it (version 1.3.0 or earlier) cannot handle genomes from viruses. I have updated TRESS (version 1.3.1 to present) to make it work for virus. 

Best,
Zhenxing

**Comment by MaestSi** [comment]
Thank you very much. Could you please upload the latest version on Bioconductor?
Thanks,
Simone

**Comment by ZhenxingGuo0015** [comment]
Hi @MaestSi,

Yes, I uploaded it to Bioconductor yesterday. But it will need some time to be compiled and published. Please wait a few days and install the development version. Thanks.

Best,
Zhenxing

**Comment by haowulab** [comment]
The one on GitHub should be immediately available. Please install from GitHub.

**Comment by MaestSi** [comment]
Dear @haowulab , thanks for the information.
I followed instructions in the readme for installation from GitHub:
```
install.packages("devtools") # if you have not installed "devtools" package
library(devtools)
install_github("https://github.com/haowulab/TRESS", build_vignettes = TRUE)
```
However, it installed TRESS_0.99.1.tar.gz, since this is the version available on the current repository. Should I install a version from a different repository?
I also tried installing v1.3.1 version with:
`install_github("https://github.com/haowulab/TRESS@1.3.1", build_vignettes = TRUE)`
but it installed v0.99.1 too.
Thanks in advance,
Simone

**Comment by haowulab** [comment]
I think Zhenxing uses a different GitHub repo to link to bioconductor. Zhenxing please confirm.

**Comment by ZhenxingGuo0015** [comment]
Hi @MaestSi,

Please install TRESS using this repo: https://github.com/ZhenxingGuo0015/TRESS/tree/master
Thanks.

Zhenxing

**Comment by MaestSi** [comment]
Thanks for the prompt replies. I was able to install TRESS v1.3.1.
I'll test it on SARS-CoV-2 genome in the coming days and let you know.
Best,
Simone

**Comment by MaestSi** [comment]
Hi,
unfortunately TRESS didn't find any peaks, but I think it worked successfully. Do you agree?
Here is the output:
```
##### Divid the genome into bins and obtain bin counts...
Time used to obtain bin-level data is: 
4.467885
##### Step 1: Call candidate peaks... 
Merge bumps from different replicates...
Time used to obtain candidates is: 
0.4326103
The number of candidates is: 
24
###### Step 2: Peak calling from candidates...
The number of Peaks in this sample is: 
0
Time used in Step 2 is: 
0.07487941
##### Done! Total time used to call peaks is: 
4.981338

```
Thank you again for the prompt replies.
Best,
Simone

**Comment by ZhenxingGuo0015** [comment]
Hi @MaestSi,

Yes, TRESS ran successfully this time.
According to the output, it seems none of the 24 candidates are significant. Then TRESS reports 0 peaks.

Zhenxing

**Comment by haowulab** [comment]
There are only 24 candidates? Maybe because the genome is too small. I'd recommend using a more loose threshold to see if you can find anything.

**Comment by haowulab** [comment]
The one on github should be immediately available.

Sent from my iPhone

On Aug 16, 2022, at 8:54 AM, ZHENXING GUO ***@***.***> wrote:

﻿

Hi @MaestSi<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaestSi&data=05%7C01%7Chao.wu%40emory.edu%7C6781375abb70458454f408da7f867f19%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637962512915196767%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r9X3BliRp%2FW0qXhR62%2B08sRIHWMMfu8No8UCglbNO54%3D&reserved=0>,

Yes, I uploaded it to Bioconductor yesterday. But it will need some time to be compiled and published. Please wait a few days and install the development version. Thanks.

Best,
Zhenxing
