### ISSUE TITLE
TRESS_1.0.0 and 1.2.0 provide very different results

### ISSUE THREAD

**Issue by MaestSi** [haowulab/TRESS#2]
Dear developers,
I have been calling peaks with one single replicate, with the following command.
```
TRESS_peak(IP.file = basename(bam_files_IP_curr),
             Input.file = basename(bam_files_input_curr),
             Path_To_AnnoSqlite = annotation_sqlite,
             InputDir = input_dir,
             OutputDir = output_dir,
             experiment_name = peaks_curr,
             filetype = "bam",
             IncludeIntron = FALSE,
             binsize = 50,
             WhichThreshold = fdr_lfc,
             pval.cutoff0 = 0.00001,
             fdr.cutoff0 = 0.05,
             lfc.cutoff0 = 0.7,
             lowcount = 30)
```
However, when using TRESS_1.0.0 I obtained 7,718 peaks, while, when using TRESS_1.2.0 I got 24 peaks. I guess in one of the two versions there might be a bug, as the difference is huge. Did you experience similar behaviour in your hands?
Thanks,
Simone

**Comment by haowulab** [comment]
Did you obtain 1.2 from bioconductor at http://bioconductor.org/packages/release/bioc/html/TRESS.html? 

Also, the GitHub repo to link to bioconductor for TRESS is: https://github.com/ZhenxingGuo0015/TRESS/tree/master. 

This repo is obsolete.

**Comment by MaestSi** [comment]
Yes, I obtained 1.2.0 from [Bioconductor](http://bioconductor.org/packages/release/bioc/html/TRESS.html) with: 
`BiocManager::install("TRESS")`
and version 1.0.0 from [bioconda](https://bioconda.github.io/recipes/bioconductor-tress/README.html#package-bioconductor-tress) with:
`conda install bioconductor-tress`
Best,
Simone

**Comment by haowulab** [comment]
We will look into this and get back to you soon.

Could you post this on https://github.com/ZhenxingGuo0015/TRESS/tree/master? Zhenxing Guo is the main developer for the method and tool.

**Comment by MaestSi** [comment]
Sure, I'll open the issue in the other GitHub repository.
Thanks in advance,
Simone
